### ISSUE TITLE
considering external link detection.

### ISSUE THREAD

**Issue by DO1JLR** [RotationMatrix/lektor-broken-links#2]
Hi there

You are writing in your README:
> "Currently it's only smart enough to check internal links [...]"

I like the idea of this plugin and really would appreciate it if this plugin can validate external links too.

I think, for most cases a test would be sufficient if the external link leads to an existing domain and if the HTTP status code 200 comes back. If necessary, extended by HTTP 301, 308 and so on...

Are there already plans to build in something like this?

**Comment by RotationMatrix** [comment]
Hello, thank you for reaching out! Apologies for my delay.

Yes, checking external links is a planned feature. I think you're right about checking the status code on the links. This could be printed to stdout as well in case of warnings or errors like HTTP 404.

How do you imagine interacting with this feature? I'm thinking this would be on-by-default with a `[Y/n]` prompt on first-run in case you would like to disable it for privacy reasons, etc. with additional configuration via environment variables like `HTTP_PROXY`.

**Comment by RotationMatrix** [comment]
This is now available with the 0.2.0 release! :tada:
